# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-10 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0003_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(default=1, upload_to='meal_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
